### ISSUE TITLE
Заявка на добавление в мод(Возможно прошу многого но рассмотри)

### ISSUE THREAD

**Issue by fexgod** [TwlghtDrgn/Operation-Destory#1]
**-Крафтовая система**
   *Добавить мусора чтобы из него крафтить вещи(банки,пустые гильзы,электроника, доски, метал. детали и т.д)
   *Если возможно узнать крафты _**Vic's Modern Warfare**_, а если нету то возможно ли сделать для него крафт.
**-Добавить предметы**
   *Фонарик, консервы(разных видов), разные виды жидкостей(вода,грязная вода,соки,алкоголь и т.д),
   *Медицина(бинты,аптечка первой помощи)
**-Разное**
   *Добавить улучшенный вид от 3-го лица(пока не обязательно)
   *Перетекстурить железный блок, а так-же по возможности всю стандартную еду майнкрафта или половину.
   *Взять во внимание мод _**First Aid**_
   *Допилить текстурпак - заменить пустующие текстуры на блоки которые не заменены, а так-же там есть 3 текстуры крови, тобишь если можно перетекстурить кровь из _**VariedCommodities**_

**Comment by TwlghtDrgn** [comment]
Заявка перемещена в TwlghtDrgn/ODAddon#1
